version: '3'
services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_USER=app
      - DB_PASSWORD=wonderful
      - DB_DATABASE=miechallenge
    depends_on:
      - db

  db:
    image: mariadb:latest
    environment:
      - MARIADB_USER=app
      - MARIADB_PASSWORD=wonderful
      - MARIADB_ROOT_PASSWORD=wonderful
      - MARIADB_DATABASE=miechallenge
    volumes:
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost"]
      interval: 10s
      timeout: 10s
      retries: 5
